[package]
name = "todomvc-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
rand = "0.8.5"
wasm-bindgen = "0.2"
wasm-logger = "0.2.0"
web-sys = "0.3.67"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
